#
# Consul Service Discovery, ~50mb
# @see https://hub.docker.com/r/progrium/consul/
# @see https://www.consul.io/docs/agent/options.html
#
consul:
  command: -server -bootstrap
  image: progrium/consul:latest
  ports:
    - 8400:8400  # rpc/rest
    - 8500:8500  # ui
    - 8600:53/udp   # dns
    - 192.168.99.101:53:53/udp  # dns

#
# Registrator Service Registry Bridge
# @see https://hub.docker.com/r/gliderlabs/registrator/
# @see http://gliderlabs.com/registrator/latest/
#
registrator:
  command: -ip=192.168.99.101 consul://consul:8500
  image: gliderlabs/registrator:latest
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
  links:
    - consul

#
# Nginx with Consul Template Support, ~40mb
# @see https://hub.docker.com/r/1science/nginx/
#
nginx:
  build: ./nginx
  links:
    - consul
  ports:
    - 80
  volumes:
    - ./nginx/templates:/etc/consul-templates
  environment:
    SERVICE_NAME: nginx

#
# A Micoservice with DNS pointing towards Consul
# That gets HTTP traffic from Nginx by route-http tag
#
service:
  build: service
  ports:
    - 5000
  volumes:
    - ./service:/code
  dns:
    - 192.168.99.101
  dns_search: service.consul
  environment:
    SERVICE_NAME: service
    SERVICE_TAGS: route-http

#
# A Statically-provisioned Redis
# @see https://hub.docker.com/_/redis/
#
redis:
  image: redis
  ports:
    - 6379:6379
  environment:
    SERVICE_NAME: redis
