consul:
  command: -server -bootstrap
  image: progrium/consul:latest
  ports:
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"
    - "192.168.99.101:53:53/udp"

registrator:
  command: -ip=192.168.99.101 consul://consul:8500
  image: gliderlabs/registrator:latest
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
  links:
    - consul

nginx:
  build: ./nginx
  links:
    - consul
  ports:
    - 80
  volumes:
    - ./nginx/templates:/etc/consul-templates
  environment:
    SERVICE_NAME: nginx

service:
  build: service
  ports:
    - 5000
  volumes:
    - ./service:/code
  links:
    - redis
  environment:
    SERVICE_NAME: service
    SERVICE_TAGS: production

redis:
  image: redis
