#
# Consul Service Discovery
# @see https://www.consul.io/docs/agent/options.html
#
consul:
  command: -server -bootstrap
  image: progrium/consul:latest
  ports:
    - 8400:8400  # rpc/rest
    - 8500:8500  # ui
    - 8600:53/udp   # dns
    - 192.168.99.101:53:53/udp  # dns

#
# Registrator Service Registry Bridge
# @see http://gliderlabs.com/registrator/latest/
#
registrator:
  command: -ip=192.168.99.101 consul://consul:8500
  image: gliderlabs/registrator:latest
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
  links:
    - consul

nginx:
  build: ./nginx
  links:
    - consul
  ports:
    - 80
  volumes:
    - ./nginx/templates:/etc/consul-templates
  environment:
    SERVICE_NAME: nginx

service:
  build: service
  ports:
    - 5000
  volumes:
    - ./service:/code
  dns:
    - 192.168.99.101
  dns_search: service.consul
  environment:
    SERVICE_NAME: service
    SERVICE_TAGS: production

redis:
  image: redis
  ports:
    - 6379:6379
  environment:
    SERVICE_NAME: redis
